# Generated by Django 4.1.9 on 2023-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-create_datetime"]},
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(fields=("stripe_payment_id", "payment_status"), name="unique payment"),
        ),
    ]
