# Generated by Django 4.1.8 on 2023-04-21 15:25

import apps.event.models
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("membership", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("organizer_email", models.EmailField(blank=True, max_length=300, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                ("registration_website", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to=apps.event.models.event_logo_file_path_func),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=50
                    ),
                ),
                ("more_data", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(editable=False, max_length=16, null=True)),
                ("prefs", models.JSONField(blank=True, editable=False, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lon", models.FloatField(blank=True, null=True)),
                ("permit_no", models.CharField(blank=True, max_length=25, null=True)),
                ("is_usac_permitted", models.BooleanField(default=False)),
                ("featured_event", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False, null=True)),
                (
                    "publish_type",
                    models.CharField(
                        choices=[("public", "Public"), ("org_public", "Org Public"), ("org_private", "Org Private")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("shared_org_perms", models.JSONField(blank=True, editable=False, null=True)),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("update_datetime", models.DateTimeField(auto_now=True)),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="membership.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("start_datetime", models.DateTimeField(null=True)),
                ("more_data", models.JSONField(blank=True, null=True)),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="races", to="event.event"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="races",
                        to="membership.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "event", "organization")},
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                (
                    "finish_status",
                    models.CharField(
                        choices=[("ok", "OK"), ("dns", "DNS"), ("dnf", "DNF")], default="ok", max_length=16
                    ),
                ),
                ("category", models.CharField(max_length=32, null=True)),
                ("more_data", models.JSONField(blank=True, null=True)),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("race", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="event.race")),
                (
                    "rider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="race_results",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "unique_together": {("rider", "race")},
            },
        ),
        migrations.CreateModel(
            name="RaceSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), null=True, size=50
                    ),
                ),
                ("points_map", models.JSONField(blank=True, null=True)),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("events", models.ManyToManyField(related_name="race_series", to="event.event")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_series",
                        to="membership.organization",
                    ),
                ),
                ("races", models.ManyToManyField(related_name="race_series", to="event.race")),
            ],
            options={
                "unique_together": {("name", "organization")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalRaceResult",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("place", models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                (
                    "finish_status",
                    models.CharField(
                        choices=[("ok", "OK"), ("dns", "DNS"), ("dnf", "DNF")], default="ok", max_length=16
                    ),
                ),
                ("category", models.CharField(max_length=32, null=True)),
                ("more_data", models.JSONField(blank=True, null=True)),
                ("create_datetime", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="event.race",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical race result",
                "verbose_name_plural": "historical race results",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EventAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=apps.event.models.event_attachment_file_path_func)),
                ("file_name", models.CharField(max_length=256)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="event.event"
                    ),
                ),
                (
                    "upload_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceSeriesResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ("more_data", models.JSONField(blank=True, null=True)),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="membership.organization"
                    ),
                ),
                ("race_result", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="event.raceresult")),
                ("race_series", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="event.raceseries")),
            ],
            options={
                "unique_together": {("race_series", "race_result", "organization")},
            },
        ),
    ]
