# Generated by Django 4.1.8 on 2023-04-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("membership", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceseries",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="race_series", to="membership.organization"
            ),
        ),
        migrations.AddField(
            model_name="raceseries",
            name="races",
            field=models.ManyToManyField(related_name="race_series", to="event.race"),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="race",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="event.race"),
        ),
    ]
