# Generated by Django 4.1.8 on 2023-04-24 13:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalEvent",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("organizer_email", models.EmailField(blank=True, max_length=300, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                ("registration_website", models.URLField(blank=True, max_length=500, null=True)),
                ("logo", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=50
                    ),
                ),
                ("more_data", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(editable=False, max_length=16, null=True)),
                ("prefs", models.JSONField(blank=True, editable=False, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lon", models.FloatField(blank=True, null=True)),
                ("permit_no", models.CharField(blank=True, max_length=25, null=True)),
                ("is_usac_permitted", models.BooleanField(default=False)),
                ("featured_event", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False, null=True)),
                (
                    "publish_type",
                    models.CharField(
                        choices=[("public", "Public"), ("org_public", "Org Public"), ("org_private", "Org Private")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("shared_org_perms", models.JSONField(blank=True, editable=False, null=True)),
                ("create_datetime", models.DateTimeField(blank=True, editable=False)),
                ("update_datetime", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="membership.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical event",
                "verbose_name_plural": "historical events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRace",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("start_datetime", models.DateTimeField(null=True)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), null=True, size=50
                    ),
                ),
                ("more_data", models.JSONField(blank=True, null=True)),
                ("create_datetime", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="event.event",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical race",
                "verbose_name_plural": "historical races",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name="race",
            unique_together={("name", "event")},
        ),
        migrations.AddField(
            model_name="historicalraceresult",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalraceresult",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="historicalraceresult",
            name="usac_license",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="race",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), null=True, size=50
            ),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="usac_license",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="raceseries",
            name="points_algorithm",
            field=models.CharField(
                choices=[("Absolute", "Absolute"), ("Relative", "Relative")],
                default="Absolute",
                max_length=16,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="RaceSeriesResult",
        ),
        migrations.RemoveField(
            model_name="race",
            name="organization",
        ),
    ]
