# Generated by Django 4.1.8 on 2023-04-24 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0002_historicalevent_historicalrace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalraceresult",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="rider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="race_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
