# Generated by Django 4.1.9 on 2023-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_event_create_by_event_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalraceseries",
            name="point_system",
            field=models.CharField(
                choices=[("Absolute", "Absolute"), ("Relative", "Relative")], max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="raceseries",
            name="point_system",
            field=models.CharField(
                choices=[("Absolute", "Absolute"), ("Relative", "Relative")], max_length=16, null=True
            ),
        ),
    ]
