# Generated by Django 4.1.9 on 2023-05-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_alter_organization_hero_alter_organization_logo"),
        ("event", "0003_historicalraceseries_point_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceseries",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="race_series",
                to="membership.organization",
            ),
        ),
    ]
