# Generated by Django 4.1.8 on 2023-04-25 15:15

import apps.event.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0003_remove_organization_email_verified_and_more"),
        ("event", "0003_alter_historicalraceresult_rider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="organizer_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="more_data",
            new_name="panels",
        ),
        migrations.RenameField(
            model_name="historicalevent",
            old_name="organizer_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="historicalevent",
            old_name="more_data",
            new_name="panels",
        ),
        migrations.RemoveField(
            model_name="event",
            name="prefs",
        ),
        migrations.RemoveField(
            model_name="event",
            name="shared_org_perms",
        ),
        migrations.RemoveField(
            model_name="event",
            name="source",
        ),
        migrations.RemoveField(
            model_name="eventattachment",
            name="upload_by",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="prefs",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="shared_org_perms",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="source",
        ),
        migrations.RemoveField(
            model_name="historicalrace",
            name="create_by",
        ),
        migrations.RemoveField(
            model_name="historicalrace",
            name="more_data",
        ),
        migrations.RemoveField(
            model_name="historicalrace",
            name="start_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalraceresult",
            name="create_by",
        ),
        migrations.RemoveField(
            model_name="race",
            name="create_by",
        ),
        migrations.RemoveField(
            model_name="race",
            name="more_data",
        ),
        migrations.RemoveField(
            model_name="race",
            name="start_datetime",
        ),
        migrations.RemoveField(
            model_name="raceresult",
            name="create_by",
        ),
        migrations.RemoveField(
            model_name="raceseries",
            name="create_by",
        ),
        migrations.RemoveField(
            model_name="raceseries",
            name="points_algorithm",
        ),
        migrations.AddField(
            model_name="event",
            name="blurb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="hero",
            field=models.ImageField(blank=True, null=True, upload_to=apps.event.models.event_hero_file_path_func),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="blurb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="hero",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalrace",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="historicalrace",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalraceresult",
            name="bib_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="historicalraceresult",
            name="club",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="historicalraceresult",
            name="gap",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="historicalraceresult",
            name="time",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="race",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="race",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="bib_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="club",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="gap",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="time",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalRaceSeries",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), null=True, size=50
                    ),
                ),
                ("points_map", models.JSONField(blank=True, null=True)),
                ("create_datetime", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="membership.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical race series",
                "verbose_name_plural": "historical race seriess",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEventAttachment",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("file", models.TextField(max_length=100)),
                ("file_name", models.CharField(max_length=256)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("create_datetime", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="event.event",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical event attachment",
                "verbose_name_plural": "historical event attachments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
