# Generated by Django 4.1.8 on 2023-04-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_rename_organizer_email_event_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="blurb",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="blurb",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
