# Generated by Django 4.1.9 on 2023-05-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_raceseries_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalraceseries",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="raceseries",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
