# Generated by Django 4.1.9 on 2023-05-12 17:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_historicalraceseries_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Road", "Road"),
                        ("Criterium", "Criterium"),
                        ("Cycle-Cross", "Cycle-Cross"),
                        ("Mountain bike", "Mountain bike"),
                        ("Hill Climb", "Hill Climb"),
                        ("Time Trial", "Time Trial"),
                        ("Gran Fondo", "Gran Fondo"),
                        ("Tour", "Tour"),
                        ("BMX", "BMX"),
                        ("Cycling Camp", "Cycling Camp"),
                        ("Clinic", "Clinic"),
                        ("Downhill", "Downhill"),
                        ("Enduro", "Enduro"),
                        ("Fat Bike", "Fat Bike"),
                        ("Gravel", "Gravel"),
                        ("Omnium", "Omnium"),
                        ("Points Race", "Points Race"),
                        ("Track", "Track"),
                        ("Stage Race", "Stage Race"),
                        ("Team Time Trial", "Team Time Trial"),
                        ("Virtual", "Virtual"),
                        ("Dual Slalom", "Dual Slalom"),
                        ("BC Road Cup", "BC Road Cup"),
                        ("BC Cycle-Cross Cup", "BC Cycle-Cross Cup"),
                        ("Collegiate Permitted", "Collegiate Permitted"),
                        ("BC State Championships", "BC State Championships"),
                        ("Youth", "Youth"),
                        ("Fundraiser", "Fundraiser"),
                    ],
                    max_length=100,
                ),
                null=True,
                size=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Road", "Road"),
                        ("Criterium", "Criterium"),
                        ("Cycle-Cross", "Cycle-Cross"),
                        ("Mountain bike", "Mountain bike"),
                        ("Hill Climb", "Hill Climb"),
                        ("Time Trial", "Time Trial"),
                        ("Gran Fondo", "Gran Fondo"),
                        ("Tour", "Tour"),
                        ("BMX", "BMX"),
                        ("Cycling Camp", "Cycling Camp"),
                        ("Clinic", "Clinic"),
                        ("Downhill", "Downhill"),
                        ("Enduro", "Enduro"),
                        ("Fat Bike", "Fat Bike"),
                        ("Gravel", "Gravel"),
                        ("Omnium", "Omnium"),
                        ("Points Race", "Points Race"),
                        ("Track", "Track"),
                        ("Stage Race", "Stage Race"),
                        ("Team Time Trial", "Team Time Trial"),
                        ("Virtual", "Virtual"),
                        ("Dual Slalom", "Dual Slalom"),
                        ("BC Road Cup", "BC Road Cup"),
                        ("BC Cycle-Cross Cup", "BC Cycle-Cross Cup"),
                        ("Collegiate Permitted", "Collegiate Permitted"),
                        ("BC State Championships", "BC State Championships"),
                        ("Youth", "Youth"),
                        ("Fundraiser", "Fundraiser"),
                    ],
                    max_length=100,
                ),
                null=True,
                size=50,
            ),
        ),
    ]
