# Generated by Django 4.1.9 on 2023-05-21 13:28

import apps.event.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_alter_event_tags_alter_historicalevent_tags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="raceseries",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historicalraceseries",
            name="logo",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="raceseries",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=apps.event.models.raceseries_logo_file_path_func),
        ),
        migrations.AlterField(
            model_name="historicalraceseries",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="raceseries",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
