# Generated by Django 4.1.10 on 2023-08-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_event_champion_event_historicalevent_champion_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="permit_no",
            field=models.CharField(blank=True, default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="publish_type",
            field=models.CharField(
                choices=[("public", "Public"), ("org_public", "Org Public"), ("org_private", "Org Private")],
                default="",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventattachment",
            name="title",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="permit_no",
            field=models.CharField(blank=True, default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="publish_type",
            field=models.CharField(
                choices=[("public", "Public"), ("org_public", "Org Public"), ("org_private", "Org Private")],
                default="",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaleventattachment",
            name="title",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalraceresult",
            name="category",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalraceresult",
            name="name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="category",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
