# Generated by Django 4.1.10 on 2023-08-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_alter_event_permit_no_alter_event_publish_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalraceresult",
            name="bib_number",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalraceresult",
            name="club",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalraceresult",
            name="gap",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalraceresult",
            name="time",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalraceresult",
            name="usac_license",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalraceseries",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalraceseries",
            name="point_system",
            field=models.CharField(
                choices=[("Absolute", "Absolute"), ("Relative", "Relative")], default="", max_length=16
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="bib_number",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="club",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="gap",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="time",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceresult",
            name="usac_license",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="raceseries",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="raceseries",
            name="point_system",
            field=models.CharField(
                choices=[("Absolute", "Absolute"), ("Relative", "Relative")], default="", max_length=16
            ),
            preserve_default=False,
        ),
    ]
