# Generated by Django 4.1.8 on 2023-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="draft",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female"), ("o", "Other"), ("u", "Unknown")], default="u", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="more_data",
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="opt_in_email",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="prefs",
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_of_service",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_agreement_waiver",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
