# Generated by Django 4.1.8 on 2023-05-03 19:40

from django.db import migrations, models
import events.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_historicaluser_name_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=events.users.models.avatar_file_path_func),
        ),
    ]
