# Generated by Django 4.1.8 on 2023-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="privacy_policy",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_policy",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
