# Generated by Django 4.1.8 on 2023-04-25 15:15

import apps.membership.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0002_alter_organizationmember_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="member_fields_schema",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="membership_plans",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="phone_verified",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="signup_config",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="verified",
        ),
        migrations.AddField(
            model_name="organization",
            name="hero",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.membership.models.organization_hero_file_path_func
            ),
        ),
    ]
