# Generated by Django 4.1.8 on 2023-05-03 19:40

import apps.membership.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="hero",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to=apps.membership.models.organization_hero_file_path_func
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to=apps.membership.models.organization_logo_file_path_func
            ),
        ),
    ]
