# Generated by Django 4.1.10 on 2023-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_alter_organization_hero_alter_organization_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("regional", "Regional"),
                    ("club", "Club"),
                    ("advocacy_volunteer", "Advocacy, Volunteer"),
                    ("photographer", "Photographer"),
                    ("promoter", "Promoter"),
                ],
                max_length=32,
            ),
        ),
    ]
